---
theme: jekyll-theme-slate
title : Welcome to Melina Houle homepage
description: Feel free to bookmark this to keep an eye on my project update
params: 
    background_img: "foret_lowres.jpg"
---


class: title-slide center middle
background-image: url(`r params$background_img`)
background-size: cover
